services:
  geoserver:
    build:
      context: .
      dockerfile: Dockerfile.geoserver
    ports:
      - "8080:8080"
    volumes:
      - geoserver_data:/opt/geoserver_data
    networks:
      - app-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - geoserver
    environment:
      - GEOSERVER_URL=http://geoserver:8080/geoserver/rest
    volumes:
      - ./src/components/server/Uploads:/app/src/components/server/Uploads
    networks:
      - app-network
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
volumes:
  geoserver_data:
networks:
  app-network:
    driver: bridge